FROM pytorch/pytorch:2.1.0-cuda11.8-cudnn8-devel

ENV TZ=US/Pacific
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apt-get update --fix-missing && \
    apt-get install -y libgtk2.0-dev && \
    apt-get install -y wget bzip2 ca-certificates curl git vim tmux g++ gcc build-essential cmake checkinstall gfortran libjpeg8-dev libtiff5-dev pkg-config yasm libavcodec-dev libavformat-dev libswscale-dev libdc1394-22-dev libxine2-dev libv4l-dev qt5-default libgtk2.0-dev libtbb-dev libatlas-base-dev libfaac-dev libmp3lame-dev libtheora-dev libvorbis-dev libxvidcore-dev libopencore-amrnb-dev libopencore-amrwb-dev x264 v4l-utils libprotobuf-dev protobuf-compiler libgoogle-glog-dev libgflags-dev libgphoto2-dev libhdf5-dev doxygen libflann-dev libboost-all-dev proj-data libproj-dev libyaml-cpp-dev cmake-curses-gui libzmq3-dev freeglut3-dev


RUN cd / && git clone https://github.com/pybind/pybind11 &&\
    cd pybind11 && git checkout v2.10.0 &&\
    mkdir build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release -DPYBIND11_INSTALL=ON -DPYBIND11_TEST=OFF &&\
    make -j6 && make install


RUN cd / && wget https://gitlab.com/libeigen/eigen/-/archive/3.4.0/eigen-3.4.0.tar.gz &&\
    tar xvzf ./eigen-3.4.0.tar.gz &&\
    cd eigen-3.4.0 &&\
    mkdir build &&\
    cd build &&\
    cmake .. &&\
    make install

SHELL ["/bin/bash", "--login", "-c"]

# Use the PyTorch base environment directly.
# Do NOT install miniconda or create a second conda env.
ENV PATH=/opt/conda/bin:$PATH
ENV TORCH_CUDA_ARCH_LIST="8.9"

RUN pip install --upgrade pip && \
    pip install "numpy<2" scipy joblib scikit-learn ruamel.yaml trimesh pyyaml \
    opencv-python imageio open3d transformations warp-lang einops \
    kornia pyrender Ninja

RUN pip install --no-build-isolation "git+https://github.com/facebookresearch/pytorch3d.git@stable"

RUN pip install --upgrade "setuptools<70" wheel

RUN cd / && git clone --recursive https://github.com/NVIDIAGameWorks/kaolin && \
    cd /kaolin && git checkout v0.15.0 && git submodule update --init --recursive

RUN cd /kaolin && \
    FORCE_CUDA=1 pip install --no-build-isolation -e .

RUN cd / && git clone https://github.com/NVlabs/nvdiffrast && \
    cd /nvdiffrast && pip install --no-build-isolation .

ENV OPENCV_IO_ENABLE_OPENEXR=1

RUN pip install scikit-image meshcat webdataset omegaconf pypng roma seaborn \
    opencv-contrib-python openpyxl wandb imgaug xlsxwriter timm albumentations \
    xatlas rtree nodejs jupyterlab objaverse g4f ultralytics==8.0.120 \
    pycocotools videoio numba && \
    conda install -y -c anaconda h5py

ENV SHELL=/bin/bash
RUN ln -sf /bin/bash /bin/sh
